<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>api</RootNamespace>
    <AssemblyName>Agrumy.Web</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="appsettings.json" />
    <None Include="appsettings.json" Condition="Exists('appsettings.json')" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Agrumy.Shared\Agrumy.Shared.csproj" />
  </ItemGroup>

</Project>
