// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Dal;

#nullable disable

namespace Agrumy.Api.Migrations.MySql.Migrations
{
    [DbContext(typeof(AgrumyDbContext))]
    [Migration("20260829182546_AddLegacyForeignKeys")]
    partial class AddLegacyForeignKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("api.Dal.Entities.DeviceConfigControllerRow", b =>
                {
                    b.Property<int>("IDDeviceConfigController")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDDeviceConfigController"));

                    b.Property<double?>("HumidHigh")
                        .HasColumnType("double");

                    b.Property<double?>("HumidLow")
                        .HasColumnType("double");

                    b.Property<double?>("LightHigh")
                        .HasColumnType("double");

                    b.Property<double?>("LightLow")
                        .HasColumnType("double");

                    b.Property<double?>("MoistHigh")
                        .HasColumnType("double");

                    b.Property<double?>("MoistLow")
                        .HasColumnType("double");

                    b.Property<int?>("Relay1")
                        .HasColumnType("int");

                    b.Property<int?>("Relay2")
                        .HasColumnType("int");

                    b.Property<int?>("Relay3")
                        .HasColumnType("int");

                    b.Property<int?>("Relay4")
                        .HasColumnType("int");

                    b.Property<int?>("Relay5")
                        .HasColumnType("int");

                    b.Property<int?>("Relay6")
                        .HasColumnType("int");

                    b.Property<int?>("Relay7")
                        .HasColumnType("int");

                    b.Property<int?>("Relay8")
                        .HasColumnType("int");

                    b.Property<bool?>("RelayEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<double?>("TempHigh")
                        .HasColumnType("double");

                    b.Property<double?>("TempLow")
                        .HasColumnType("double");

                    b.Property<double?>("WaterHigh")
                        .HasColumnType("double");

                    b.Property<double?>("WaterLow")
                        .HasColumnType("double");

                    b.HasKey("IDDeviceConfigController");

                    b.HasIndex("Relay1");

                    b.HasIndex("Relay2");

                    b.HasIndex("Relay3");

                    b.HasIndex("Relay4");

                    b.HasIndex("Relay5");

                    b.HasIndex("Relay6");

                    b.HasIndex("Relay7");

                    b.HasIndex("Relay8");

                    b.ToTable("deviceConfigController", (string)null);
                });

            modelBuilder.Entity("api.Dal.Entities.DeviceConfigSensorRow", b =>
                {
                    b.Property<int>("IDDeviceConfigSensor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDDeviceConfigSensor"));

                    b.Property<int?>("SensorBarometer")
                        .HasColumnType("int");

                    b.Property<int?>("SensorBattery")
                        .HasColumnType("int");

                    b.Property<int?>("SensorCo2")
                        .HasColumnType("int");

                    b.Property<int?>("SensorHumid")
                        .HasColumnType("int");

                    b.Property<int?>("SensorLight")
                        .HasColumnType("int");

                    b.Property<int?>("SensorMoist")
                        .HasColumnType("int");

                    b.Property<int?>("SensorPH")
                        .HasColumnType("int");

                    b.Property<int?>("SensorRainLevel")
                        .HasColumnType("int");

                    b.Property<int?>("SensorTemp")
                        .HasColumnType("int");

                    b.Property<int?>("SensorTempSoil")
                        .HasColumnType("int");

                    b.Property<int?>("SensorTvoc")
                        .HasColumnType("int");

                    b.Property<int?>("SensorWaterLevel")
                        .HasColumnType("int");

                    b.Property<int?>("SensorWind")
                        .HasColumnType("int");

                    b.HasKey("IDDeviceConfigSensor");

                    b.HasIndex("SensorBarometer");

                    b.HasIndex("SensorBattery");

                    b.HasIndex("SensorCo2");

                    b.HasIndex("SensorHumid");

                    b.HasIndex("SensorLight");

                    b.HasIndex("SensorMoist");

                    b.HasIndex("SensorPH");

                    b.HasIndex("SensorRainLevel");

                    b.HasIndex("SensorTemp");

                    b.HasIndex("SensorTempSoil");

                    b.HasIndex("SensorTvoc");

                    b.HasIndex("SensorWaterLevel");

                    b.HasIndex("SensorWind");

                    b.ToTable("deviceConfigSensor", (string)null);
                });

            modelBuilder.Entity("api.Dal.Entities.DeviceFirmwareRow", b =>
                {
                    b.Property<int>("IDDeviceFirmware")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDDeviceFirmware"));

                    b.Property<DateTime?>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("DeviceTypeID")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.Property<string>("Version")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IDDeviceFirmware");

                    b.ToTable("deviceFirmware", (string)null);
                });

            modelBuilder.Entity("api.Dal.Entities.DeviceRow", b =>
                {
                    b.Property<int>("IDDevice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDDevice"));

                    b.Property<string>("ApiId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool?>("BatteryEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("ConfigVersion")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DateModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool?>("Debug")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("DeviceConfigControllerID")
                        .HasColumnType("int");

                    b.Property<int?>("DeviceConfigSensorID")
                        .HasColumnType("int");

                    b.Property<bool?>("DeviceControllerEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool?>("DeviceSensorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("DeviceTypeID")
                        .HasColumnType("int");

                    b.Property<int?>("DeviceTypeServiceID")
                        .HasColumnType("int");

                    b.Property<int?>("DeviceUnitID")
                        .HasColumnType("int");

                    b.Property<int?>("DeviceUnitZoneID")
                        .HasColumnType("int");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("FirmwareUpdate")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MacAddress")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<bool?>("Reboot")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Reset")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ServicePoint")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ServicePublicKey")
                        .HasColumnType("longtext");

                    b.Property<bool?>("SleepDeepEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("SleepSeconds")
                        .HasColumnType("int");

                    b.Property<int?>("TenantID")
                        .HasColumnType("int");

                    b.HasKey("IDDevice");

                    b.HasIndex("ApiId")
                        .IsUnique()
                        .HasDatabaseName("ApiID_UNIQUE");

                    b.HasIndex("DeviceConfigControllerID");

                    b.HasIndex("DeviceConfigSensorID");

                    b.HasIndex("DeviceTypeID");

                    b.HasIndex("DeviceTypeServiceID");

                    b.HasIndex("DeviceUnitID");

                    b.HasIndex("TenantID");

                    b.ToTable("device", (string)null);
                });

            modelBuilder.Entity("api.Dal.Entities.DeviceTypeRelayRow", b =>
                {
                    b.Property<int>("IDDeviceTypeRelay")
                        .HasColumnType("int");

                    b.Property<string>("RelayName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("IDDeviceTypeRelay");

                    b.ToTable("deviceTypeRelay", (string)null);
                });

            modelBuilder.Entity("api.Dal.Entities.DeviceTypeRow", b =>
                {
                    b.Property<int>("IDDeviceType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDDeviceType"));

                    b.Property<bool?>("ControllerEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DeviceTypeName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("SensorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("IDDeviceType");

                    b.ToTable("deviceType", (string)null);
                });

            modelBuilder.Entity("api.Dal.Entities.DeviceTypeSensorRow", b =>
                {
                    b.Property<int>("IDDeviceTypeSensor")
                        .HasColumnType("int");

                    b.Property<int?>("Barometer")
                        .HasColumnType("int");

                    b.Property<int?>("Battery")
                        .HasColumnType("int");

                    b.Property<int?>("Co2")
                        .HasColumnType("int");

                    b.Property<int?>("Humidity")
                        .HasColumnType("int");

                    b.Property<int?>("Light")
                        .HasColumnType("int");

                    b.Property<int?>("Moisture")
                        .HasColumnType("int");

                    b.Property<int?>("RainLevel")
                        .HasColumnType("int");

                    b.Property<string>("SensorDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("SensorName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int?>("Temperature")
                        .HasColumnType("int");

                    b.Property<int?>("TemperatureSoil")
                        .HasColumnType("int");

                    b.Property<int?>("Tvoc")
                        .HasColumnType("int");

                    b.Property<int?>("WaterPH")
                        .HasColumnType("int");

                    b.Property<int?>("WaterTankLevel")
                        .HasColumnType("int");

                    b.Property<int?>("Wind")
                        .HasColumnType("int");

                    b.HasKey("IDDeviceTypeSensor");

                    b.ToTable("deviceTypeSensor", (string)null);
                });

            modelBuilder.Entity("api.Dal.Entities.DeviceTypeServiceRow", b =>
                {
                    b.Property<int>("IDDeviceTypeService")
                        .HasColumnType("int");

                    b.Property<string>("ServiceType")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.HasKey("IDDeviceTypeService");

                    b.ToTable("deviceTypeService", (string)null);
                });

            modelBuilder.Entity("api.Dal.Entities.DeviceUnitRow", b =>
                {
                    b.Property<int>("IDDeviceUnit")
                        .HasColumnType("int");

                    b.Property<string>("DeviceUnitName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("DeviceUnitZoneID")
                        .HasColumnType("int");

                    b.Property<bool?>("ZoneEnabled")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("IDDeviceUnit");

                    b.HasIndex("DeviceUnitZoneID");

                    b.ToTable("deviceUnit", (string)null);
                });

            modelBuilder.Entity("api.Dal.Entities.DeviceUnitZoneRow", b =>
                {
                    b.Property<int>("IDDeviceUnitZone")
                        .HasColumnType("int");

                    b.Property<string>("DeviceUnitZoneName")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("IDDeviceUnitZone");

                    b.ToTable("deviceUnitZone", (string)null);
                });

            modelBuilder.Entity("api.Dal.Entities.EventDeviceRow", b =>
                {
                    b.Property<int>("IDEventDevice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDEventDevice"));

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DeviceID")
                        .HasColumnType("int");

                    b.Property<int>("EventID")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.HasKey("IDEventDevice");

                    b.ToTable("eventDevice", (string)null);
                });

            modelBuilder.Entity("api.Dal.Entities.EventServiceRow", b =>
                {
                    b.Property<int>("IDEventService")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDEventService"));

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EventID")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<int>("ServiceID")
                        .HasColumnType("int");

                    b.HasKey("IDEventService");

                    b.ToTable("eventService", (string)null);
                });

            modelBuilder.Entity("api.Dal.Entities.SensorDataReportRow", b =>
                {
                    b.Property<int>("IDSensorDataReport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDSensorDataReport"));

                    b.Property<DateTime?>("DateGenerated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("DeviceID")
                        .HasColumnType("int")
                        .HasColumnName("deviceID");

                    b.Property<string>("ReportName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("SensorData")
                        .HasColumnType("longtext")
                        .HasColumnName("sensorData");

                    b.HasKey("IDSensorDataReport");

                    b.HasIndex("DeviceID");

                    b.ToTable("sensorDataReport", (string)null);
                });

            modelBuilder.Entity("api.Dal.Entities.SensorDataRow", b =>
                {
                    b.Property<int>("IDSensorData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDSensorData"));

                    b.Property<double?>("Barometer")
                        .HasColumnType("double");

                    b.Property<int?>("Battery")
                        .HasColumnType("int");

                    b.Property<int?>("Co2")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DeviceID")
                        .HasColumnType("int");

                    b.Property<int>("DeviceUnitID")
                        .HasColumnType("int");

                    b.Property<int>("DeviceUnitZoneID")
                        .HasColumnType("int");

                    b.Property<double?>("Humidity")
                        .HasColumnType("double");

                    b.Property<int?>("Light")
                        .HasColumnType("int");

                    b.Property<double?>("LiquidPH")
                        .HasColumnType("double");

                    b.Property<int?>("Moisture")
                        .HasColumnType("int");

                    b.Property<int?>("RainLevel")
                        .HasColumnType("int");

                    b.Property<double?>("SoilTemperature")
                        .HasColumnType("double");

                    b.Property<double?>("Temperature")
                        .HasColumnType("double");

                    b.Property<int>("TenantID")
                        .HasColumnType("int");

                    b.Property<int?>("Tvoc")
                        .HasColumnType("int");

                    b.Property<int?>("WaterLevel")
                        .HasColumnType("int");

                    b.Property<int?>("Wind")
                        .HasColumnType("int");

                    b.HasKey("IDSensorData");

                    b.HasIndex("DeviceUnitID");

                    b.HasIndex("DeviceUnitZoneID");

                    b.HasIndex("DeviceID", "TenantID", "DateCreated")
                        .HasDatabaseName("ix_sensorData_device_tenant_date");

                    b.ToTable("sensorData", (string)null);
                });

            modelBuilder.Entity("api.Dal.Entities.ServerConfigRow", b =>
                {
                    b.Property<int>("IDServerConfig")
                        .HasColumnType("int");

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("JWTKey")
                        .HasColumnType("longtext");

                    b.Property<int?>("PortHTTP")
                        .HasColumnType("int");

                    b.Property<int?>("PortHTTPS")
                        .HasColumnType("int");

                    b.Property<string>("ServerConfigCol")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("serverConfigcol");

                    b.Property<string>("ServerConfigName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IDServerConfig");

                    b.ToTable("serverConfig", (string)null);
                });

            modelBuilder.Entity("api.Dal.Entities.TenantRow", b =>
                {
                    b.Property<int>("IDTenant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDTenant"));

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IDTenant");

                    b.HasIndex("TenantName")
                        .IsUnique()
                        .HasDatabaseName("Name_UNIQUE");

                    b.ToTable("tenant", (string)null);
                });

            modelBuilder.Entity("api.Dal.Entities.UserGroupRow", b =>
                {
                    b.Property<int>("IDUserGroup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDUserGroup"));

                    b.Property<string>("GroupName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int?>("UserRoleID")
                        .HasColumnType("int");

                    b.HasKey("IDUserGroup");

                    b.HasIndex("UserRoleID");

                    b.ToTable("userGroup", (string)null);
                });

            modelBuilder.Entity("api.Dal.Entities.UserRoleRow", b =>
                {
                    b.Property<int>("IDUserRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDUserRole"));

                    b.Property<string>("RoleName")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<int?>("RoleScopeID")
                        .HasColumnType("int");

                    b.HasKey("IDUserRole");

                    b.HasIndex("RoleScopeID");

                    b.ToTable("userRole", (string)null);
                });

            modelBuilder.Entity("api.Dal.Entities.UserRoleScopeRow", b =>
                {
                    b.Property<int>("IDRoleScope")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDRoleScope"));

                    b.Property<string>("RoleScopeName")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("IDRoleScope");

                    b.ToTable("userRoleScope", (string)null);
                });

            modelBuilder.Entity("api.Dal.Entities.UserRow", b =>
                {
                    b.Property<int>("IDUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDUser"));

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DateModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("DevicePin")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("PwdHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PwdSalt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("TenantID")
                        .HasColumnType("int");

                    b.Property<int?>("UserGroupID")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IDUser");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("email_UNIQUE");

                    b.HasIndex("UserGroupID");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("Username_UNIQUE");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("api.Dal.Entities.DeviceConfigControllerRow", b =>
                {
                    b.HasOne("api.Dal.Entities.DeviceTypeRelayRow", null)
                        .WithMany()
                        .HasForeignKey("Relay1")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Dal.Entities.DeviceTypeRelayRow", null)
                        .WithMany()
                        .HasForeignKey("Relay2")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Dal.Entities.DeviceTypeRelayRow", null)
                        .WithMany()
                        .HasForeignKey("Relay3")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Dal.Entities.DeviceTypeRelayRow", null)
                        .WithMany()
                        .HasForeignKey("Relay4")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Dal.Entities.DeviceTypeRelayRow", null)
                        .WithMany()
                        .HasForeignKey("Relay5")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Dal.Entities.DeviceTypeRelayRow", null)
                        .WithMany()
                        .HasForeignKey("Relay6")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Dal.Entities.DeviceTypeRelayRow", null)
                        .WithMany()
                        .HasForeignKey("Relay7")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Dal.Entities.DeviceTypeRelayRow", null)
                        .WithMany()
                        .HasForeignKey("Relay8")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("api.Dal.Entities.DeviceConfigSensorRow", b =>
                {
                    b.HasOne("api.Dal.Entities.DeviceTypeSensorRow", null)
                        .WithMany()
                        .HasForeignKey("SensorBarometer")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Dal.Entities.DeviceTypeSensorRow", null)
                        .WithMany()
                        .HasForeignKey("SensorBattery")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Dal.Entities.DeviceTypeSensorRow", null)
                        .WithMany()
                        .HasForeignKey("SensorCo2")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Dal.Entities.DeviceTypeSensorRow", null)
                        .WithMany()
                        .HasForeignKey("SensorHumid")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Dal.Entities.DeviceTypeSensorRow", null)
                        .WithMany()
                        .HasForeignKey("SensorLight")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Dal.Entities.DeviceTypeSensorRow", null)
                        .WithMany()
                        .HasForeignKey("SensorMoist")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Dal.Entities.DeviceTypeSensorRow", null)
                        .WithMany()
                        .HasForeignKey("SensorPH")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Dal.Entities.DeviceTypeSensorRow", null)
                        .WithMany()
                        .HasForeignKey("SensorRainLevel")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Dal.Entities.DeviceTypeSensorRow", null)
                        .WithMany()
                        .HasForeignKey("SensorTemp")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Dal.Entities.DeviceTypeSensorRow", null)
                        .WithMany()
                        .HasForeignKey("SensorTempSoil")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Dal.Entities.DeviceTypeSensorRow", null)
                        .WithMany()
                        .HasForeignKey("SensorTvoc")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Dal.Entities.DeviceTypeSensorRow", null)
                        .WithMany()
                        .HasForeignKey("SensorWaterLevel")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Dal.Entities.DeviceTypeSensorRow", null)
                        .WithMany()
                        .HasForeignKey("SensorWind")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("api.Dal.Entities.DeviceRow", b =>
                {
                    b.HasOne("api.Dal.Entities.DeviceConfigControllerRow", null)
                        .WithMany()
                        .HasForeignKey("DeviceConfigControllerID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Dal.Entities.DeviceConfigSensorRow", null)
                        .WithMany()
                        .HasForeignKey("DeviceConfigSensorID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Dal.Entities.DeviceTypeRow", null)
                        .WithMany()
                        .HasForeignKey("DeviceTypeID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Dal.Entities.DeviceTypeServiceRow", null)
                        .WithMany()
                        .HasForeignKey("DeviceTypeServiceID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Dal.Entities.DeviceUnitRow", null)
                        .WithMany()
                        .HasForeignKey("DeviceUnitID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Dal.Entities.TenantRow", null)
                        .WithMany()
                        .HasForeignKey("TenantID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("api.Dal.Entities.DeviceUnitRow", b =>
                {
                    b.HasOne("api.Dal.Entities.DeviceUnitZoneRow", null)
                        .WithMany()
                        .HasForeignKey("DeviceUnitZoneID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("api.Dal.Entities.SensorDataReportRow", b =>
                {
                    b.HasOne("api.Dal.Entities.DeviceRow", null)
                        .WithMany()
                        .HasForeignKey("DeviceID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("api.Dal.Entities.SensorDataRow", b =>
                {
                    b.HasOne("api.Dal.Entities.DeviceRow", null)
                        .WithMany()
                        .HasForeignKey("DeviceID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("api.Dal.Entities.DeviceUnitRow", null)
                        .WithMany()
                        .HasForeignKey("DeviceUnitID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("api.Dal.Entities.DeviceUnitZoneRow", null)
                        .WithMany()
                        .HasForeignKey("DeviceUnitZoneID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Dal.Entities.UserGroupRow", b =>
                {
                    b.HasOne("api.Dal.Entities.UserRoleRow", null)
                        .WithMany()
                        .HasForeignKey("UserRoleID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("api.Dal.Entities.UserRoleRow", b =>
                {
                    b.HasOne("api.Dal.Entities.UserRoleScopeRow", null)
                        .WithMany()
                        .HasForeignKey("RoleScopeID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("api.Dal.Entities.UserRow", b =>
                {
                    b.HasOne("api.Dal.Entities.UserGroupRow", null)
                        .WithMany()
                        .HasForeignKey("UserGroupID")
                        .OnDelete(DeleteBehavior.NoAction);
                });
#pragma warning restore 612, 618
        }
    }
}
